### ISSUE TITLE
Identify existing issue categories

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/omeka-theme-seasons#1]
*Work In Progress*

The following tickets have been created as a result of the production launch of the Tell Us How UC It Omeka site. 

The task in this ticket is to categorize tickets based on the following categories:

* Theme Layer (i.e. can be addressed in this repository)
* Omeka Plugin Issue
* Omeka Core Issue

**Comment by dt-ucsd** [comment]
#2 - Theme Layer
#3 - Theme Layer
#4 - Theme Layer
#5 - Theme Layer
#6 - Theme Layer
#7  - Theme Layer
#8 - Omeka Plugin Issue
#9 - Omeka Plugin Issue
