### ISSUE TITLE
Change "Sort" date type

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/omeka-theme-seasons#5]
**Issue:**

- Currently, the default sort type is by Date Added. Make it sort by **Date.**

![image2017-2-2 18-35-11](https://cloud.githubusercontent.com/assets/4314914/24420892/3f57d110-13a9-11e7-884d-39bdf24f0ed4.png)

**Related resource:** 
- http://omeka.org/forums-legacy/topic/how-can-one-make-itemsbrowse-default-to-sorting-by-date

**Comment by dt-ucsd** [comment]
Looks like both of these files will need to be updated if we want the change in both places:

/collections/browse.php
/items/browse.php

**Comment by dt-ucsd** [comment]
Note that "Dublin Core,Date" is a string and is sorted lexicographically.
