### ISSUE TITLE
Sorting by Creator does not display the results

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/omeka-theme-seasons#6]
**Issue:**

- When you sort by Creator, creator(s) doesn't actually display in the results.
- Investigate how to make them display in the UI results.

![image2017-2-2 18-36-22](https://cloud.githubusercontent.com/assets/4314914/24421068/d56c093c-13a9-11e7-9f6d-4fc14e8a675f.png)

**Comment by dt-ucsd** [comment]
Added Creator metadata to Description container:

![image](https://cloud.githubusercontent.com/assets/2448340/25412702/83a43da4-29d9-11e7-8570-fd23816525eb.png)

_Note: If Creator is an empty string it won't display._
