### ISSUE TITLE
Investigate lifting character limit on collection description

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/omeka-theme-seasons#7]
**Issue:**

- Look to see if there is a way to increase the character limit on the collection description.

![image2017-2-2 18-36-22](https://cloud.githubusercontent.com/assets/4314914/24421238/632a4ffe-13aa-11e7-8e67-74ad3bf69081.png)

**Comment by dt-ucsd** [comment]
Update description's length via: *'snippet'=>MAX_LENGTH_VALUE*

(items/browse.php)

_Default: application/views/scripts/items_

**Comment by dt-ucsd** [comment]
@gamontoya What would you like the updated character limit to be?

**Comment by dt-ucsd** [comment]
**Original values:**

collections/browse.php: 'snippet'=>150
items/browse.php: 'snippet'=>250

**Updated values:**

collections/browse.php: 'snippet'=>1000
items/browse.php: 'snippet'=>1000
