### ISSUE TITLE
R&D on searching PDFs

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/omeka-theme-seasons#8]
**Issue:**

- Neither PDF Text 1.0 nor PDF Text 1.0.1 could be installed - when activating the [Install] button nothing occurs.
- Investigate and advise on other options for searching PDFs.

**Comment by dt-ucsd** [comment]
"The following error occurred while installing the PdfText plugin: The pdftotext command-line utility is not installed. pdftotext must be installed to install this plugin."

**Comment by mcritchlow** [comment]
Thanks @dt-ucsd ! @jhriv will look into this for Sprint 08

**Comment by jhriv** [comment]
I've installed the `doppler-utils` package to provide `pdftotext`.

**Comment by jhriv** [comment]
Did this fix the issue?

**Comment by gamontoya** [comment]
@jhriv The plugin now installs fine on the dev Omeka instance. Can you install it on https://library.ucsd.edu/tellushowucit/ 

- Do you need a new ticket for that?
- If so, JIRA, github?

**Comment by mcritchlow** [comment]
@gamontoya @jhriv did we wrap this one up? wondering if it should be closed.

**Comment by gamontoya** [comment]
@mcritchlow @jhriv This should not be closed as the work on the prod instance was not done.

**Comment by gamontoya** [comment]
@mcritchlow Accidentally closed this. How can ir

**Comment by gamontoya** [comment]
@jhriv If you're working on Omeka stuff today, maybe you can install the doppler-utils package to *tellushowucit* prod.

**Comment by jhriv** [comment]
Deployed the updated seasons theme to TellUsHow UCit

**Comment by mcritchlow** [comment]
@gamontoya sounds like we can close this one out? (thanks @jhriv !)
